### ISSUE TITLE
How to start the app?

### ISSUE THREAD

**Issue by tukusejssirs** [lubo/archlinux-eidklient#1]
Hey, @lubo! Thanks for trying to improve the app to make it possible run it on Wayland, however, I have failed to run it without `xcb` platform plugin.

All I did is as follows:

1. `git clone git@github.com:lubo/archlinux-eidklient.git`;
2. `(cd archlinux-eidklient && makepkg -si)`;
3. `eidklient`;
4. `QT_QPA_PLATFORM='xcb' eidklient`.

Without `xcb`, I get the following error:

```bash
QSocketNotifier: Can only be used with threads started with QThread
This application failed to start because it could not find or load the Qt platform plugin "wayland"
in "/tmp/.mount_eidkliMwlZSR/plugins/".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
```

I have `qt5-wayland@5.15.10+kde+r51-1` installed.

How do you run it to make it work on Wayland?

Thanks in advance! :pray:

**Comment by lubo** [comment]
Hi. It looks like you aren't actually using my changes. Check out `improvements` branch and build the package from there. The package won't contain `eidklient` executable and you will have to use `eID_Client` instead.

As it seems like you aren't experiencing any problems with my changes, I'm closing the issue. I will reopen if it turns out that there really is a problem.

**Comment by tukusejssirs** [comment]
Nice catch! Yeah, it’s my mistake I have not checked out the `improvements` branch. And yeah, `eID_Client` works as expected.

Thanks for your time and improving eID Client! :pray:
